spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg_homework
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: Bana54321bana3024 #${PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher